# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factorial.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("factorial.proto", :syntax => :proto3) do
    add_message "factorial.FactorialRequest" do
      optional :number, :uint64, 1
    end
    add_message "factorial.FactorialResponse" do
      optional :result, :string, 1
    end
  end
end

module Factorial
  FactorialRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("factorial.FactorialRequest").msgclass
  FactorialResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("factorial.FactorialResponse").msgclass
end
