# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: factorial.proto for package 'factorial'

require 'grpc'
require 'factorial_pb'

module Factorial
  module FactorialService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'factorial.FactorialService'

      rpc :GetFactorial, ::Factorial::FactorialRequest, ::Factorial::FactorialResponse
    end

    Stub = Service.rpc_stub_class
  end
end
